a = input('digite algo')
print('o tipo primitivo desse valor e', type(a))
print('so tem espaços', a.isspace())
print('é um numero',a.isnumeric())
print('é alfabetico',a.isalpha())
print('é alfanumerico',a.isalnum())
print('é maisculo',a.isupper())
print('é minusculo',a.islower())
print('está capitalizado',a.istitle())
